name: copy publish/* from kumablog
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    name: copy publish/*
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone kumablog
        uses: actions/checkout@v2
        with:
          repository: kumashun8/kumablog
          path: kumablog
          token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
      - name: copy kumablog/public/*
        run: cp -rfp kumablog/public/* ./
      - name: clean kumablog
        run: rm -rf kumablog
      - name: git config
        run: |
          git config --local user.email "tiwo3wa4@gmail.com"
          git config --local user.name "kumashun8"
      - name: commit files
        run: |
          git add .
          git commit -m "publish new pages" -a
          git pull
          git push origin master
      # - name: create PR
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     commit-message: '🎉 publish new pages'
      #     branch: master
      #     branch-suffix: timestamp
      #     delete-branch: true
      #     title: 'publish new pages'
