name: publish kumablog/public/* to GitHub Pages
on:
  repository_dispatch:
    types: [public-updated]
jobs:
  publish-kumablog:
    name: publish-kumablog
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone kumablog
        uses: actions/checkout@v2
        with:
          repository: kumashun8/kumablog
          path: kumablog
          token: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}
      - name: copy kumablog/public/*
        run: cp -rfp kumablog/public/* ./
      - name: clean kumablog
        run: rm -rf kumablog
      - name: git config
        run: |
          git config --local user.name $GITHUB_USER_NAME
          git config --local user.email $GITHUB_USER_MAIL
        env: |
          GITHUB_USER_NAME: kumashun8
          GITHUB_USER_MAIL: tiwo3wa4@gmail.com
      - name: commit files
        run: |
          git add .
          git commit -m "publish new pages" -a
          git pull
          git push origin master
